version: '2'

volumes:
  nextcloud:
  db:

secrets:
  mysql_root_pass:
    file: ./mysql_root_pass.txt
  mysql_pass:
    file: ./mysql_pass.txt

services:
  db:
    image: ghcr.io/linuxserver/mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_pass
      - FILE__MYSQL_PASSWORD=/run/secrets/mysql_pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    secrets:
      - mysql_root_pass
      - mysql_pass

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_pass
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    secrets:
      - mysql_pass
    restart: always
  